#Write SQL queries to perform the following tasks using the Sakila database:

#List the number of films per category.
#Retrieve the store ID, city, and country for each store.
#Calculate the total revenue generated by each store in dollars.
#Determine the average running time of films for each category.
SELECT COUNT(film_id), name
FROM film as f 
inner join film_category as f_c
using(film_id)
inner join category as c
using(category_id)
group by name
order by COUNT(film_id) desc;
#Retrieve the store ID, city, and country for each store.
SELECT store_id ,city, country
from store
inner join address
using( address_id)
inner join city
using(city_id)
inner join country
using(country_id);
#Calculate the total revenue generated by each store in dollars.
select sum(payment.amount) ,store.store_id 
from store
inner join staff
using(store_id)
inner join payment
using(staff_id)
group by store.store_id;
#Determine the average running time of films for each category.
SELECT avg(length), name
FROM film as f 
inner join film_category as f_c
using(film_id)
inner join category as c
using(category_id)
group by name
order by avg(length) desc;
#Identify the film categories with the longest average running time.
SELECT avg(length), name
FROM film as f 
inner join film_category as f_c
using(film_id)
inner join category as c
using(category_id)
group by name
order by avg(length) desc;
#Display the top 10 most frequently rented movies in descending order.
select sum(film.rental_duration) , title from film
group by title
order by sum(rental_duration) desc
limit 10;
#Determine if "Academy Dinosaur" can be rented from Store 1.
select inventory.store_id, film.title
from film
inner join inventory
using(film_id)
group by inventory.store_id 
having film.title = "Academy Dinosaur";

#Provide a list of all distinct film titles, along with their availability status in the inventory. Include a column indicating whether each title is 'Available' or 'NOT available.' Note that there are 42 titles that are not in the inventory, and this information can be obtained using a CASE statement combined with IFNULL."